### ISSUE TITLE
Build the new V2.8.0 source code - 2 issues

### ISSUE THREAD

**Issue by RadioOperator** [SiliconLabs/EFRConnect-android#32]
Hi, I've try to build the v2.8.0,    Two issues:

1. run App - [press Demo] - [press Scan] on the bottom nav bar, Logcat will see the error:
```
Failed to inflate ColorStateList, leaving it to the framework
                                                                                                    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f04010e a=-1}, theme={InheritanceMap=[id=0x7f1402abcom.siliconlabs.bledemo:style/ThemeOverlay.Material3.Button.IconButton, id=0x7f1402aecom.siliconlabs.bledemo:style/ThemeOverlay.Material3.Button.TextButton], Themes=[com.siliconlabs.bledemo:style/ThemeOverlay.Material3.Button.IconButton, forced, com.siliconlabs.bledemo:style/MainAppTheme, forced, com.siliconlabs.bledemo:style/CustomSplashTheme, forced, com.siliconlabs.bledemo:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                                                                                                    	at android.content.res.TypedArray.getColor(TypedArray.java:529)

.........................

at com.siliconlabs.bledemo.common.views.ExpandArrow.<init>(ExpandArrow.kt:8)

........................

at com.siliconlabs.bledemo.databinding.AdapterBrowserDeviceBinding.inflate(AdapterBrowserDeviceBinding.java:104)
at com.siliconlabs.bledemo.databinding.AdapterBrowserDeviceBinding.inflate(AdapterBrowserDeviceBinding.java:98)

```

2. In the Demo page, press [Matter Demo], App crashed immediately. The logcat reports:
```
Shutting down VM
E  FATAL EXCEPTION: main
Process: com.siliconlabs.bledemo, PID: 26430
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~7JmyRpIQLugiQF2OSp5tfw==/com.siliconlabs.bledemo-aLo8HfzF3G0HtRUVF_PMMA==/base.apk!/lib/arm64-v8a/libCHIPController.so" has bad ELF magic: 76657273

at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
at java.lang.System.loadLibrary(System.java:1661)
at chip.devicecontroller.ChipDeviceController.<clinit>(ChipDeviceController.java:1081)
at com.siliconlabs.bledemo.features.demo.matter_demo.utils.ChipClient.getAndroidChipPlatform(ChipClient.kt:49)
at com.siliconlabs.bledemo.features.demo.matter_demo.utils.ChipClient.getDeviceController(ChipClient.kt:33)
at com.siliconlabs.bledemo.features.demo.matter_demo.activities.MatterDemoActivity.onCreate(MatterDemoActivity.kt:73)
at android.app.Activity.performCreate(Activity.java:8944)
at android.app.Activity.performCreate(Activity.java:8913)

```
seems the lib file - CHIPController.jar  with error/bugs.

Please help to check the problems, thanks.

**Comment by RadioOperator** [comment]
Those 2 errors, still in the new v2.9.0 release.

**Comment by silabs-SachithM** [comment]
Issue is fixed. Please test in the latest version of the code base.
